"""Initial migration

Revision ID: 143cbf422770
Revises: 
Create Date: 2025-01-07 15:37:22.328148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '143cbf422770'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.alter_column('favourites', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favourites', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_favourites_product_id'), 'favourites', ['product_id'], unique=False)
    op.create_index(op.f('ix_favourites_user_id'), 'favourites', ['user_id'], unique=False)
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'tag',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.add_column('roles', sa.Column('level', sa.Integer(), nullable=True))
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_roles_id', table_name='roles')
    op.alter_column('rusers', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('rusers', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_rusers_id', table_name='rusers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rusers_id', 'rusers', ['id'], unique=False)
    op.alter_column('rusers', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('rusers', 'username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_index('ix_roles_id', 'roles', ['id'], unique=False)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('roles', 'level')
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('products', 'tag',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_favourites_user_id'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_product_id'), table_name='favourites')
    op.alter_column('favourites', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favourites', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_table('sample',
    sa.Column('idno', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emailid', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('idno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
